# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-07 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pps_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistentry',
            name='BlacklistKey',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='whitelistentry',
            name='WhitelistEntry',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
